name: Storefront deployment
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - test
      - release
  pull_request:
    branches:
      - main
      - test

jobs:
  deploy-storefront:
      uses: AndrewEhlo/test-actions/.github/workflows/storefront.yml@main
