name: Storefront deployment
on:
  workflow_dispatch:
    inputs:
      deployBranch: 
        description: 'ArgoCd branch name'
        required: true
        default: 'dev'

jobs:
  deploy-storefront:
      uses: AndrewEhlo/test-actions/.github/workflows/storefront.yml@main
