name: Post welcome comment
on:
  workflow_dispatch:
  pull_request:
    types: [opened]
jobs:
  build:
    name: Post welcome comment
    runs-on: ubuntu-latest
    steps:
      - name: Test script
        if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'workflow_dispatch' }}
        run: |
          echo "Test message"
