name: Post welcome comment
on:
  workflow_dispatch:
  pull_request:
    types: [opened]
jobs:
  build:
    name: Post welcome comment
    runs-on: ubuntu-latest
    steps:
      #- run: gh pr comment $PR_URL --body "Welcome to the repository!"
      #  env:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #    PR_URL: ${{ github.event.pull_request.html_url }}
      - uses: actions/upload-artifact@v3
        with:
          name: harness-build-log
          path: var/log/dmesg*
