name: Post welcome comment
on:
  workflow_dispatch:
  push:
    branches:
      [master, dev]
  pull_request:
    branches:
      [master, dev]
jobs:
  build:
    name: Post welcome comment
    env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - name: Create GH Release
        run: |
          gh release create v1.0.0 --title "My Release" --notes "This is my release notes"
