name: Post welcome comment
on:
  workflow_dispatch:
  push:
    branches:
      [master, dev]
  pull_request #:
    #branches:
     # [master, dev]
jobs:
  build:
    name: Post welcome comment
    env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Add link to PR
        if: ${{ github.event_name == 'pull_request' }}
        uses: VirtoCommerce/vc-github-actions/publish-artifact-link@master
        with:
          artifactUrl: ${{ github.event_name }}
          repoOrg: ${{ github.repository_owner }}
          downloadComment: 'Artifact URL:'
