name: Post welcome comment
on:
  workflow_dispatch:
  push:
    branches:
      [master, dev]
  pull_request:
    branches:
      [master, dev]
jobs:
  build:
    name: Post welcome comment
    env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get changelog
        id: changelog
        uses: VirtoCommerce/vc-github-actions/changelog-generator@master  
      - name: Create Release
        id: create_release
        with:
          changelog: ${{ steps.changelog.outputs.changelog }}
          organization: ${{ github.repository_owner }}
        uses: VirtoCommerce/vc-github-actions/publish-github-release@master
